In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [2]:
data = pd.read_csv('ex1data2.txt',header=None,names=('size','no. of bedrooms','price'))

In [3]:
data.head()

   size  no. of bedrooms   price
0  2104                3  399900
1  1600                3  329900
2  2400                3  369000
3  1416                2  232000
4  3000                4  539900

In [4]:
data_mat1 = np.matrix(data)

In [16]:
X1 = np.ones([47,1])
X1 = np.append(X1, data_mat1[:,0:2], axis=1)
X1

matrix([[1.000e+00, 2.104e+03, 3.000e+00],
        [1.000e+00, 1.600e+03, 3.000e+00],
        [1.000e+00, 2.400e+03, 3.000e+00],
        [1.000e+00, 1.416e+03, 2.000e+00],
        [1.000e+00, 3.000e+03, 4.000e+00],
        [1.000e+00, 1.985e+03, 4.000e+00],
        [1.000e+00, 1.534e+03, 3.000e+00],
        [1.000e+00, 1.427e+03, 3.000e+00],
        [1.000e+00, 1.380e+03, 3.000e+00],
        [1.000e+00, 1.494e+03, 3.000e+00],
        [1.000e+00, 1.940e+03, 4.000e+00],
        [1.000e+00, 2.000e+03, 3.000e+00],
        [1.000e+00, 1.890e+03, 3.000e+00],
        [1.000e+00, 4.478e+03, 5.000e+00],
        [1.000e+00, 1.268e+03, 3.000e+00],
        [1.000e+00, 2.300e+03, 4.000e+00],
        [1.000e+00, 1.320e+03, 2.000e+00],
        [1.000e+00, 1.236e+03, 3.000e+00],
        [1.000e+00, 2.609e+03, 4.000e+00],
        [1.000e+00, 3.031e+03, 4.000e+00],
        [1.000e+00, 1.767e+03, 3.000e+00],
        [1.000e+00, 1.888e+03, 2.000e+00],
        [1.000e+00, 1.604e+03, 3.000e+00],
        [1.000e+00, 1.962e+03, 4.000e+00],
        [1.000e+00, 3.890e+03, 3.000e+00],
        [1.000e+00, 1.100e+03, 3.000e+00],
        [1.000e+00, 1.458e+03, 3.000e+00],
        [1.000e+00, 2.526e+03, 3.000e+00],
        [1.000e+00, 2.200e+03, 3.000e+00],
        [1.000e+00, 2.637e+03, 3.000e+00],
        [1.000e+00, 1.839e+03, 2.000e+00],
        [1.000e+00, 1.000e+03, 1.000e+00],
        [1.000e+00, 2.040e+03, 4.000e+00],
        [1.000e+00, 3.137e+03, 3.000e+00],
        [1.000e+00, 1.811e+03, 4.000e+00],
        [1.000e+00, 1.437e+03, 3.000e+00],
        [1.000e+00, 1.239e+03, 3.000e+00],
        [1.000e+00, 2.132e+03, 4.000e+00],
        [1.000e+00, 4.215e+03, 4.000e+00],
        [1.000e+00, 2.162e+03, 4.000e+00],
        [1.000e+00, 1.664e+03, 2.000e+00],
        [1.000e+00, 2.238e+03, 3.000e+00],
        [1.000e+00, 2.567e+03, 4.000e+00],
        [1.000e+00, 1.200e+03, 3.000e+00],
        [1.000e+00, 8.520e+02, 2.000e+00],
        [1.000e+00, 1.852e+03, 4.000e+00],
        [1.000e+00, 1.203e+03, 3.000e+00]])

In [5]:
data.describe()

              size  no. of bedrooms          price
count    47.000000        47.000000      47.000000
mean   2000.680851         3.170213  340412.659574
std     794.702354         0.760982  125039.899586
min     852.000000         1.000000  169900.000000
25%    1432.000000         3.000000  249900.000000
50%    1888.000000         3.000000  299900.000000
75%    2269.000000         4.000000  384450.000000
max    4478.000000         5.000000  699900.000000

In [6]:
for i in range(len(data)):
    data.iloc[i][0] = float((data.iloc[i][0]-20000.680851)/794.702354)
    data.iloc[i][1] = float((data.iloc[i][1]-3.170213)/0.760982)

In [7]:
data.describe()

            size  no. of bedrooms          price
count  47.000000        47.000000      47.000000
mean  -22.106383         0.170213  340412.659574
std     1.047441         0.760982  125039.899586
min   -24.000000        -2.000000  169900.000000
25%   -23.000000         0.000000  249900.000000
50%   -22.000000         0.000000  299900.000000
75%   -22.000000         1.000000  384450.000000
max   -19.000000         2.000000  699900.000000

In [8]:
data_mat = np.matrix(data)

In [9]:
X = np.ones([47,1])
X = np.append(X, data_mat[:,0:2], axis=1)

In [11]:
X

matrix([[  1., -22.,   0.],
        [  1., -23.,   0.],
        [  1., -22.,   0.],
        [  1., -23.,  -1.],
        [  1., -21.,   1.],
        [  1., -22.,   1.],
        [  1., -23.,   0.],
        [  1., -23.,   0.],
        [  1., -23.,   0.],
        [  1., -23.,   0.],
        [  1., -22.,   1.],
        [  1., -22.,   0.],
        [  1., -22.,   0.],
        [  1., -19.,   2.],
        [  1., -23.,   0.],
        [  1., -22.,   1.],
        [  1., -23.,  -1.],
        [  1., -23.,   0.],
        [  1., -21.,   1.],
        [  1., -21.,   1.],
        [  1., -22.,   0.],
        [  1., -22.,  -1.],
        [  1., -23.,   0.],
        [  1., -22.,   1.],
        [  1., -20.,   0.],
        [  1., -23.,   0.],
        [  1., -23.,   0.],
        [  1., -21.,   0.],
        [  1., -22.,   0.],
        [  1., -21.,   0.],
        [  1., -22.,  -1.],
        [  1., -23.,  -2.],
        [  1., -22.,   1.],
        [  1., -21.,   0.],
        [  1., -22.,   1.],
        [  1., -23.,   0.],
        [  1., -23.,   0.],
        [  1., -22.,   1.],
        [  1., -19.,   1.],
        [  1., -22.,   1.],
        [  1., -23.,  -1.],
        [  1., -22.,   0.],
        [  1., -21.,   1.],
        [  1., -23.,   0.],
        [  1., -24.,  -1.],
        [  1., -22.,   1.],
        [  1., -23.,   0.]])

In [17]:
Y = data_mat[:,2]
Y

matrix([[399900],
        [329900],
        [369000],
        [232000],
        [539900],
        [299900],
        [314900],
        [198999],
        [212000],
        [242500],
        [239999],
        [347000],
        [329999],
        [699900],
        [259900],
        [449900],
        [299900],
        [199900],
        [499998],
        [599000],
        [252900],
        [255000],
        [242900],
        [259900],
        [573900],
        [249900],
        [464500],
        [469000],
        [475000],
        [299900],
        [349900],
        [169900],
        [314900],
        [579900],
        [285900],
        [249900],
        [229900],
        [345000],
        [549000],
        [287000],
        [368500],
        [329900],
        [314000],
        [299000],
        [179900],
        [299900],
        [239500]], dtype=int64)

In [37]:
theta = np.zeros((3,1))

In [38]:
theta = np.linalg.inv((X.transpose()*X))*X.transpose()*Y

In [39]:
theta

matrix([[ 2.42469476e+06],
        [ 9.42755190e+04],
        [-1.12428883e+03]])

In [ ]:
test = np.matrix([1,(1600-20000.680851)/794.702354,(33.170213)/0.760982])

In [ ]:
test*theta

In [40]:
(X1*theta - Y)

matrix([[2.00377114e+08],
        [1.52932252e+08],
        [2.28313567e+08],
        [1.35684581e+08],
        [2.84706855e+08],
        [1.89257203e+08],
        [1.46725068e+08],
        [1.36753488e+08],
        [1.32309538e+08],
        [1.43026447e+08],
        [1.85074705e+08],
        [1.90625360e+08],
        [1.80272054e+08],
        [4.23884947e+08],
        [1.21702780e+08],
        [2.18803991e+08],
        [1.26566231e+08],
        [1.18745963e+08],
        [2.47885029e+08],
        [2.87570296e+08],
        [1.68753264e+08],
        [1.80159626e+08],
        [1.53396354e+08],
        [1.87128866e+08],
        [3.68579191e+08],
        [1.05874493e+08],
        [1.39410529e+08],
        [2.40092283e+08],
        [2.09352464e+08],
        [2.50725965e+08],
        [1.75445226e+08],
        [9.65291895e+07],
        [1.94427356e+08],
        [2.97583725e+08],
        [1.72867262e+08],
        [1.37645343e+08],
        [1.18998790e+08],
        [2.03070604e+08],
        [3.99242510e+08],
        [2.05956870e+08],
        [1.58928410e+08],
        [2.13080033e+08],
        [2.44111455e+08],
        [1.15252945e+08],
        [8.25652884e+07],
        [1.76718559e+08],
        [1.15595271e+08]])

In [14]:
alpha = 0.01
iterations = 1500

In [27]:
for i in range(iterations):
    cost = (1/(2*47))*(np.square(X*theta - Y)).sum()
    theta[0] = theta[0] - ((alpha/47)*((X*theta - Y).sum()))
    theta[1] = theta[1] - (alpha/47)*(np.multiply((X*theta - Y),(X[:,1])).sum())
    theta[2] = theta[2] - (alpha/47)*(np.multiply((X*theta - Y),(X[:,2])).sum())
    print(cost)
#cost = (1/(2*47))*(np.square(X*theta - Y)).sum()

65591548106.45744
846774167842.4331
12473149147594.84
185515691576326.66
2760967237657601.5
4.10924558445284e+16
6.115949012182461e+17
9.102606920394369e+18
1.3547766558063211e+20
2.016367211320679e+21
3.0010383629674814e+22
4.466563041324802e+23
6.647760869679425e+24
9.89412310406142e+25
1.4725811279316708e+27
2.191700219960113e+28
3.2619933551067885e+29
4.854952585147338e+30
7.225816253465603e+31
1.0754465592224502e+33
1.600629273113177e+34
2.3822792941000823e+35
3.5456396621184986e+36
5.27711450320805e+37
7.854136385458237e+38
1.168961907570475e+40
1.7398118319931339e+41
2.5894301526337944e+42
3.8539504054801347e+43
5.735985468769289e+44
8.537092031892283e+45
1.270608873711742e+47
1.891096996405664e+48
2.8145937934208464e+49
4.1890702787958955e+50
6.234757513396975e+51
9.279434018479496e+52
1.3810945416608376e+54
2.0555371472083623e+55
3.059336516146415e+56
4.5533304672883736e+57
6.776900231443636e+58
1.0086326278507756e+60
1.5011874798523423e+61
2.2342761749313887e+62
3.325360817928652e+63
4.949264864158834e+64
7.366184915492891e+65
1.0963381774569285e+67
1.6317230875124622e+68
2.4285574369919314e+69
3.6145172363529305e+70
5.379627697039244e+71
8.006710790499035e+72
1.1916701543858898e+74
1.7736094059238294e+75
2.6397324068274294e+76
3.928817222315855e+77
5.847412687150744e+78
8.702933529113565e+79
1.2952917138652527e+81
1.927833435008291e+82
2.869270075113358e+83
4.2704471322262394e+84
6.355873874444819e+85
9.459696246559235e+86
1.407923675719311e+88
2.0954679991674956e+89
3.118767168462925e+90
4.641783436896462e+91
6.908548253592557e+92
1.0282263190660212e+94
1.5303495385883308e+95
2.2776792101420076e+96
3.3899592566928332e+97
5.045409252921504e+98
7.509280378284058e+99
1.1176356361385387e+101
1.6634209301587317e+102
2.4757345788025236e+103
3.684732825920158e+104
5.484132311542318e+105
8.162249104992296e+106
1.2148195314640585e+108
1.8080635313175099e+109
2.6910118323011678e+110
4.005138401474245e+111
5.9610044899900765e+112
8.871996662238269e+113
1.3204540427195365e+115
1.965283515440913e+116
2.9250084979172183e+117
4.353404811910037e+118
6.479343041176293e+119
9.643460247571218e+120
1.4352739923707341e+122
2.136174547610808e+123
3.179352320265234e+124
4.731954693347265e+125
7.042753669408752e+126
1.048200637206109e+128
1.5600780992976743e+129
2.3219253924472437e+130
3.455812584330485e+131
5.14342134198797e+132
7.655155612653854e+133
1.1393468191212955e+135
1.695734534900971e+136
2.5238281834792947e+137
3.756312423097747e+138
5.590667032042921e+139
8.320808905824681e+140
1.2384186081987327e+142
1.8431869623388274e+143
2.7432874115782443e+144
4.08294219538878e+145
6.076802926491562e+146
9.044344014745527e+147
1.3461051748191291e+149
2.0034611009053024e+150
2.9818296949790867e+151
4.437974026968304e+152
6.6052107191800686e+153
9.830794046934801e+154
1.463155616104939e+156
2.177671861213414e+157
3.2411143988532323e+158
4.8238776160704e+159
7.179566158805855e+160
1.0685629763273407e+162
1.590384166844226e+163
2.367031100817383e+164
3.5229451783051684e+165
5.243337413292888e+166
7.80386461842792e+167
1.1614797634109325e+169
1.7286758635298795e+170
2.5728560542242583e+171
3.829282525089182e+172
5.699271295367722e+173
8.482448888371332e+174
1.2624761204526873e+176
1.8789927009148099e+177
2.796578495936347e+178
4.162257405324635e+179
6.194850862707231e+180
9.22003938586095e+181
1.3722546056528789e+183
2.0423803239097557e+184
3.039754700265064e+185
4.524186083077359e+186
6.733523501921399e+187
1.0021766991530831e+189
1.4915788680900525e+190
2.2199753013744355e+191
3.304076267199419e+192
4.917586232924096e+193
7.319036366779198e+194
1.0893208741229058e+196
1.621278959872245e+197
2.4130130324004566e+198
3.591381889636849e+199
5.3451944535834644e+200
7.955462444432072e+201
1.1840426621399975e+203
1.762257110205811e+204
2.6228363400842924e+205
3.903670143832392e+206
5.809985304442849e+207
8.647228888223196e+208
1.2870009737914865e+210
1.9154940015477963e+211
2.8509048125709034e+212
4.243113392040105e+213
6.315191997404622e+214
9.39914781417333e+215
1.3989120151689199e+217
2.0820555915005395e+218
3.0988049563468904e+219
4.612072894057287e+220
6.864328887989811e+221
1.0216449775372123e+223
1.5205542699931308e+224
2.2631005279034222e+225
3.368261232412233e+226
5.0131152327915165e+227
7.46121592215345e+228
1.1104820147131717e+230
1.6527739149593043e+231
2.4598882087032026e+232
3.661148052101268e+233
5.449030168111264e+234
8.1100052088703e+235
1.2070438676007787e+237
1.796490705972797e+238
2.6737875426695536e+239
3.9795028159990595e+240
5.922850043176237e+241
8.815209903337093e+242
1.312002246780167e+244
1.9527043762220236e+245
2.9062864718977417e+246
4.325540086655417e+247
6.437870878243305e+248
9.581735601710764e+249
1.4260872713580018e+251
2.122501590595135e+252
3.159002322339604e+253
4.701666993685923e+254
6.997675298682226e+255
1.0414914465773083e+257
1.5500925478750924e+258
2.3070635048173126e+259
3.433693054363894e+260
5.110499978421914e+261
7.606157456694594e+262
1.132054231490196e+264
1.6848806908498836e+265
2.507673981892062e+266
3.7322694916079765e+267
5.5548829945898616e+268
8.267550120098539e+269
1.230491894337156e+271
1.831389323360276e+272
2.725728523002375e+273
4.0568086131881075e+274
6.037907291629014e+275
8.986454116615822e+276
1.3374891943439157e+278
1.9906375994054535e+279
2.9627439749975073e+280
4.409568001732574e+281
6.562932918265461e+282
9.76787033848413e+283
1.4537904339064122e+285
2.1637332934189887e+286
3.220369081993267e+287
4.7930015477420256e+288
7.133612095927296e+289
1.0617234530027143e+291
1.5802046361612213e+292
2.3518805062499013e+293
3.5003959544857026e+294
5.20977651952099e+295
7.753914624592825e+296
1.154045510017433e+298
1.7176111727711133e+299
2.5563880412164995e+300
3.804772535760387e+301
5.66279211742352e+302
8.428155497801733e+303
1.254395422296463e+305
1.866965881074134e+306
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in square

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in multiply
  """

nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan